"use client";

import { Lightbulb } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { InsightData } from "@/lib/types";

type InsightCardProps = {
  insight: InsightData | null;
  onGenerate: () => void | Promise<void>;
  isGenerating: boolean;
};

export function InsightCard({ insight, onGenerate, isGenerating }: InsightCardProps) {
  return (
    <div className="bg-pulse-surface border border-pulse-border rounded-xl overflow-hidden">
      <div className="h-0.5 w-full bg-pulse-primary" />
      <div className="p-4">
        <p className="text-[11px] font-mono uppercase tracking-widest text-pulse-text-muted mb-2">
          AI INSIGHT · NOT A DIAGNOSIS
        </p>
        <div className="flex items-start gap-2 mb-3">
          <Lightbulb className="w-5 h-5 text-pulse-primary shrink-0 mt-0.5" />
          <div>
            <h3 className="font-medium text-pulse-text-primary">Pattern detected</h3>
            {insight ? (
              <>
                <p className="text-pulse-text-secondary text-sm mt-2">{insight.summary}</p>
                {insight.patterns?.length > 0 && (
                  <div className="flex flex-wrap gap-2 mt-3">
                    {insight.patterns.slice(0, 3).map((p, i) => (
                      <span
                        key={i}
                        className="text-xs px-2 py-1 rounded-md bg-pulse-primary/10 text-pulse-text-secondary"
                      >
                        {p.feature} → mood (r={p.confidence?.toFixed(2) ?? ""}, lag {p.lag_days}d)
                      </span>
                    ))}
                  </div>
                )}
                <p className="text-xs text-pulse-text-muted mt-3">
                  Generated by {insight.model_used}. Behavioral pattern analysis only.
                </p>
              </>
            ) : (
              <p className="text-pulse-text-muted text-sm mt-2">
                {isGenerating ? "Analyzing 30 days…" : "Analyzing your patterns…"}
              </p>
            )}
          </div>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={onGenerate}
          disabled={isGenerating}
          className="border-pulse-border text-pulse-text-secondary"
        >
          {isGenerating ? "Analyzing…" : "Generate new analysis →"}
        </Button>
      </div>
    </div>
  );
}
